[build]
  base = "/"
  command = "apt-get update && apt-get install -y ninja-build && export PATH=/opt/build/repo/cpp/build/cmake/bin:$PATH && npm run setup-cmake && npm run netlify-build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  Emscripten = "true"
  CMAKE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
